### ISSUE TITLE
🔧 Settings

### ISSUE THREAD

**Issue by loidnoir** [Noir-bot/Noir-bot#15]
# Settings
Settings command to control all settings for commands and events
## TODO
- [ ] General page with options (moderation, welcome)
- [ ] Moderation page (moderation roles, restriction role, logs channel, logs types)
- [ ] Welcome page (message, channel, role)
